### ISSUE TITLE
Get Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by lightondust** [deeuu/loudness#5]
Thanks for the work.

After installation, I run the following sample code

```
import loudness as ln

# All inputs and outputs make use of a SignalBank
inputBank = ln.SignalBank()
nSources = 1
nEars = 1
nChannels = 1
nSamples = 1
fs = 1

# There are 4 dimensions
inputBank.initialize(nSources, nEars, nChannels, nSamples, fs)

# Set the centre frequency of the first channel
inputBank.setCentreFreq(0, 1000)

# Set the intensity in normalised units
level = 40
inputBank.setSample(0, 0, 0, 0, 10.0 ** (level / 10.0))

# The loudness model
model = ln.StationaryLoudnessANSIS342007()
model.initialize(inputBank)

# Now process the input
model.process(inputBank)

# Get the output of this loudness model
feature = 'InstantaneousLoudness'
outputBank = model.getOutput(feature)

print('Loudness in sones %0.2f' % outputBank.getSample(0, 0, 0, 0))
```

And got the following messages

```
/home/sen/env/ml/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Segmentation fault (core dumped)
```

It seems the problem occurs at

```
outputBank.getSample(0, 0, 0, 0)
```

Do you have an idea of this problem?

I have tried python 2.7 and python 3.6.
OS: ubuntu 16.04.6
gcc: 5.4.0
g++: 5.4.0

Thanks

**Comment by deeuu** [comment]
Hey, I'm away from computer until next week so will take a look myself then, but looks like an update to h5py / numpy. 

Take a look at https://github.com/h5py/h5py/issues/961

**Comment by lightondust** [comment]
Thank you for the information.
I updated h5py to v2.9.0, the warning message disappears but still get the Segmentation fault.

**Comment by deeuu** [comment]
Hi,

It looks like the feature name (for time-invariant models) is `Loudness` and not `InstantaneousLoudness`.
I've updated the README to reflect this.

Sorry for the poor documentation, I'm hoping to revive this project when I have time...

**Comment by lightondust** [comment]
thanks for answering
